In [2]:
# Задание 1
import numpy as np
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [3]:
# Задание 2
b1 = a.reshape(3, 4)
b1

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [4]:
b2 = a.reshape(4, 3)
b2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [5]:
b3 = a.reshape(2, 6)
b3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [6]:
b4 = a.reshape(2, 2, 3)
b4

array([[[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [7]:
b5 = a.reshape(2, 3, 2)
b5

array([[[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [8]:
# Задание 3
с1 = a.reshape(4, -1)
с1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
с2 = a.reshape(6, -1)
с2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
с3 = a.reshape(2, -1)
с3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [11]:
с4 = a.reshape(-1, 6)
с4

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [12]:
с4 = a.reshape(-1, 3)
с4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [13]:
# Задание 4
print('Да')

Да


In [14]:
# Задание 5
d = np.random.randn(3, 4)
d

array([[-4.39492300e-02,  2.38459456e+00, -9.56705141e-01,
        -9.65002421e-02],
       [-4.95578492e-04, -1.62445781e-01, -7.17402713e-01,
         1.83041132e+00],
       [ 1.92289373e-01,  3.65892940e-01, -1.13521064e+00,
        -3.74643923e-01]])

In [15]:
d_one_size = d.flatten()
d_one_size

array([-4.39492300e-02,  2.38459456e+00, -9.56705141e-01, -9.65002421e-02,
       -4.95578492e-04, -1.62445781e-01, -7.17402713e-01,  1.83041132e+00,
        1.92289373e-01,  3.65892940e-01, -1.13521064e+00, -3.74643923e-01])

In [16]:
# Задание 6
# 1й способ
a = np.arange(2, 22, 2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [17]:
a[::-1].sort()
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [18]:
# 2й способ
a = np.arange(2, 22, 2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [19]:
a = [a[-1], a[-2], a[-3], a[-4], a[-5], a[-6], a[-7], a[-8], a[-9], a[-10]]
print(a)

[20, 18, 16, 14, 12, 10, 8, 6, 4, 2]


In [20]:
# Задание 7
b = np.arange(2, 22, 2)
b[::-1].sort()
print(b)
print('Нет разницы')

[20 18 16 14 12 10  8  6  4  2]
Нет разницы


In [21]:
# Задание 8
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [22]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
v = np.vstack((a, b))
print(v)
print('Атрибут size массива v равен', v.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Атрибут size массива v равен 10


In [24]:
# Задание 9
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
At = np.transpose(A)
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [27]:
B = A.dot(At)
print(B)
print('Матрица B имеет размер', B.size)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
Матрица B имеет размер 16


In [28]:
opred = np.linalg.det(B)
print('Обратную матрицу B посчитать нельзя, потому что ее определитель =', opred)

Обратную матрицу B посчитать нельзя, потому что ее определитель = 0.0


In [29]:
# Задание 10
np.random.seed(42)

In [30]:
# Задание 11
c = np.random.randint(0, 16, (1, 16))
c

array([[ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4]])

In [31]:
# Задание 12
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [32]:
# способ 1
D = C * 10 + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [33]:
opred1 = np.linalg.det(D)
print('Определитель =', opred1)
r1 = np.linalg.matrix_rank(D)
print('Ранг =', r1)
D_inv1 = np.linalg.inv(D)
print('Обратная матрица D =', D_inv1)

Определитель = -28511999.999999944
Ранг = 4
Обратная матрица D = [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


In [34]:
# способ 2
D = np.add(C.dot(10), B)
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [35]:
opred2 = np.linalg.det(D)
print('Определитель =', opred2)
r2 = np.linalg.matrix_rank(D)
print('Ранг =', r2)
D_inv2 = np.linalg.inv(D)
print('Обратная матрица D =', D_inv2)

Определитель = -28511999.999999944
Ранг = 4
Обратная матрица D = [[ 0.00935396  0.04486532  0.05897517 -0.07286055]
 [-0.01503577 -0.00122896 -0.00192971  0.00967873]
 [-0.00356692 -0.01782828 -0.04152146  0.04326178]
 [ 0.00909091 -0.00181818  0.01272727 -0.01090909]]


In [36]:
# Задание 13
D_inv = np.where(D_inv2 < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [37]:
# для наглядности
print('B =', B)
print('C =', C)

B = [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
C = [[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]


In [38]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])