In [39]:
#задание 1
import numpy as np
a = np.array([[1, 6],[2, 8],[3, 11],[3, 10],[1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [14]:
#задание 2
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [18]:
#задание3
a_centered_sp = a_centered[:,0].dot(a_centered[:,1])
a_centered_sp

8.0

In [53]:
N = len(a_centered)
N
a_centered_sp / (N-1)

2.0

In [41]:
#задание 4
m = np.transpose(a)
m


array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [50]:
a_cov = np.cov(m)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])